name: Commit every hour

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make a commit
      env:
        AUTO_TOKEN: ${{ secrets.AUTO_TOKEN }}
      run: |
        echo "$(date)" > commit.txt
        git config --global user.name "eddieem"
        git config --global user.email "edward.emeka@owasp.org"
        git add commit.txt
        git commit -m "Automated commit $(date)"
        git push
