name: Commit Changes

on:
  schedule:
    - cron: '0 * * * *' # This runs the action every hour

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        # Your commands to make changes go here
        echo "Automated commit $(date)" >> commit.txt

    - name: Commit changes
      run: |
        git config --global user.email "edward.emeka@owasp.org"
        git config --global user.name "eddieem"
        git add .
        git commit -m "Automated commit $(date)"
        git push
      env:
        AUTO_TOKEN: ${{ secrets.AUTO_TOKEN }}
