name: Commit every hour

on:
  workflow_dispatch:
  schedule:
    # Run every hour on Mondays, Wednesdays, and Fridays
    - cron: '0 * * * 1,3,5'
    # Run every 6 hours on Sundays, Tuesdays, Thursdays, and Saturdays
    - cron: '0 */6 * * 0,2,4,6'

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make a commit
      env:
        AUTO_TOKEN: ${{ secrets.AUTO_TOKEN }}
      run: |
        echo "$(date)" > commit.txt
        git config --global user.name "eddieem"
        git config --global user.email "edward.emeka@owasp.org"
        git add commit.txt
        git commit -m "Automated commit $(date)"
        git push
